dist: precise
language: node_js
node_js:
  - "node"
  - 6
  - 7
  - 8
install: true
before_script: npm i -g yarn
script:
  - yarn -i
  - yarn predeploy
  - yarn postdeploy
  - yarn global add npm-check-updates
  - ncu
  - ncu -u
  - yarn -i
  - yarn upgrade
cache:
  directories:
    - node_modules
